export const restaurantRegions = [
  { id: "all", label: "全部地區" },
  { id: "city", label: "新竹市區" },
  { id: "zhubei", label: "竹北" },
  { id: "zhudong", label: "竹東" },
  { id: "guanpu", label: "關埔・園區" },
];

export const restaurantCategories = [
  { id: "all", label: "全部類型" },
  { id: "japanese", label: "日式" },
  { id: "chinese", label: "中式" },
  { id: "snack", label: "台式・小吃" },
  { id: "late", label: "宵夜" },
  { id: "hotpot", label: "火鍋" },
  { id: "thai", label: "南洋・泰式" },
  { id: "indian", label: "印度・咖哩" },
];

export const restaurantPriceTiers = [
  { id: "all", label: "全部價位" },
  { id: "value", label: "NT$200 內" },
  { id: "mid", label: "NT$201–500" },
  { id: "premium", label: "NT$501 以上" },
];

export const restaurantMeals = [
  { id: "all", label: "不限時段" },
  { id: "lunch", label: "午餐" },
  { id: "dinner", label: "晚餐" },
  { id: "late", label: "深夜" },
];

export const restaurantTagLabels = {
  japanese: "日式",
  chinese: "中式",
  snack: "台式・小吃",
  late: "宵夜",
  hotpot: "火鍋",
  thai: "南洋・泰式",
  indian: "印度・咖哩",
};

export const restaurants = [
  {
    id: "city-duck-rice",
    name: "廟口鴨香飯・中正店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 150,
    hours: "週一、四至日 11:00–15:00、15:30–20:40；週二、三休",
    address: "新竹市北區中正路 258 號",
    signature: "鴨香飯、鴨肉與在地小吃",
    note: "適合一個人快速吃，也適合把小菜分著點。尖峰時段通常需要候位。",
    parking: "建議步行或機車；開車可找北門街、中正路周邊停車場。",
    sourceLabel: "FonFood｜近期營業資訊",
    sourceUrl: "https://www.fonfood.com/store/258557",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=廟口鴨香飯中正店",
  },
  {
    id: "city-sishi-skewers",
    name: "私嚐串燒・中正店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["japanese", "late"],
    meals: ["dinner", "late"],
    budget: 700,
    hours: "週日至四 18:00–01:30；週五、六 18:00–02:00",
    address: "新竹市東區中正路 96 巷 8 號",
    signature: "串燒、居酒屋與深夜聚餐",
    note: "官方帳號可查訂位方式；多人聚餐或週末晚餐建議先訂位。",
    parking: "位於城隍廟商圈，建議搭車或步行；開車可利用府後街停車場。",
    sourceLabel: "私嚐｜LINE 官方帳號",
    sourceUrl: "https://page.line.me/kuu0879e",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=私嚐串燒中正店",
  },
  {
    id: "city-shinbashi-yakiniku",
    name: "新橋燒肉屋・府後店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["japanese"],
    meals: ["lunch", "dinner"],
    budget: 900,
    hours: "11:30–14:30、17:30–24:00；訂位與臨時異動依店家公告",
    address: "新竹市東區府後街 9 號",
    signature: "日式燒肉、約會與多人聚餐",
    note: "預算以每人約 NT$900 估算；實際依肉品與酒水選擇浮動。",
    parking: "可利用府後街停車場；週末晚餐時段建議預留找車位時間。",
    sourceLabel: "新橋燒肉｜官方訂位資訊",
    sourceUrl: "https://www.shinchiao.com.tw/shinbashi_yakiniku/reservation.asp",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=新橋燒肉屋府後店",
  },
  {
    id: "city-yenchiang-hotpot",
    name: "岩漿火鍋・新竹經國店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["chinese", "hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 800,
    hours: "每日 11:00–03:00；最後入場 02:00",
    address: "新竹市北區東大路二段 78 號",
    signature: "麻辣火鍋、聚餐與深夜熱食",
    note: "跨午餐到深夜都能用；宵夜時段仍建議先確認當日候位狀況。",
    parking: "店家分店資訊標示有停車服務，仍以現場安排為準。",
    sourceLabel: "岩漿火鍋｜官方分店資訊",
    sourceUrl: "https://yenchiang-hotpot.com/index.php/branch/get_has_navi_page/1",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=岩漿火鍋新竹經國店",
  },
  {
    id: "city-duanchunzhen",
    name: "段純貞牛肉麵・新竹建功店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 300,
    hours: "週二至五 11:30–14:00、17:30–20:30；週末午餐至 14:30；週一休",
    address: "新竹市東區建功一路 135 號",
    signature: "紅燒牛肉麵與眷村風味",
    note: "清楚、好決定的一餐，適合交大商圈活動前後安排。",
    parking: "建功一路車位有限，機車較方便；開車可找赤土崎公園周邊停車場。",
    sourceLabel: "段純貞｜官方門市資訊",
    sourceUrl: "https://www.duanchunzhen.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=段純貞新竹建功店",
  },
  {
    id: "city-sukiya-station",
    name: "すき家・新竹站前店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["japanese", "indian"],
    meals: ["lunch", "dinner"],
    budget: 180,
    hours: "每日 10:00–22:00；最後點餐 21:30",
    address: "新竹市東區民族路 21 號 1 樓",
    signature: "牛丼、日式咖哩與一人快速用餐",
    note: "火車站附近的平價日式選擇；牛丼與咖哩都能把預算控制在 NT$200 左右。",
    parking: "新竹車站步行可達；開車建議使用後站或林森路停車場。",
    sourceLabel: "すき家｜官方店舖資訊",
    sourceUrl: "https://www.sukiya-jp.com.tw/shoplist/hsinchu.html",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=すき家新竹站前店",
  },
  {
    id: "city-sukiya-nanya",
    name: "すき家・新竹湳雅店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["japanese", "indian"],
    meals: ["lunch", "dinner"],
    budget: 180,
    hours: "每日 10:00–22:00；最後點餐 21:30",
    address: "新竹市北區大雅路 88 號 1 樓",
    signature: "牛丼、日式咖哩與湳雅逛街補給",
    note: "位於大魯閣湳雅廣場，停車與順路採買都方便，也補上第二間平價日式／咖哩選擇。",
    parking: "可使用大魯閣湳雅廣場停車場，折抵方式依商場公告。",
    sourceLabel: "すき家｜官方店舖資訊",
    sourceUrl: "https://www.sukiya-jp.com.tw/shoplist/hsinchu.html",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=すき家新竹湳雅店",
  },
  {
    id: "city-sushiro-bigcity",
    name: "壽司郎・新竹巨城店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["japanese"],
    meals: ["lunch", "dinner"],
    budget: 450,
    hours: "週日至四 11:00–21:30；週五、六 11:00–22:00；依商場公告為準",
    address: "新竹市東區中央路 229 號 7 樓",
    signature: "迴轉壽司、多人各取所需與親子用餐",
    note: "餐盤計價、預算好控制；週末熱門時段建議先用官方 App 取號。",
    parking: "可使用遠東巨城停車場，消費折抵依商場規則。",
    sourceLabel: "壽司郎｜官方店舖資訊",
    sourceUrl: "https://www.sushiro.com.tw/Shop/ShopInfo?shopId=150",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=壽司郎新竹巨城店",
  },
  {
    id: "city-six-doors-guangfu",
    name: "六扇門時尚湯鍋・新竹光復店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 190,
    hours: "每日 11:00–02:00；臨時異動依店家公告",
    address: "新竹市東區光復路一段 89 巷 12 號",
    signature: "百元個人鍋、自助吧與竹科深夜熱食",
    note: "平價火鍋和宵夜兩種需求一次補上；近期查核資料標示營業到凌晨 2 點。",
    parking: "光復路與金山街周邊停車不易，機車或叫車較省時間。",
    sourceLabel: "愛七桃｜2026 店家查核",
    sourceUrl: "https://tw.i7tou.com/%E5%85%AD%E6%89%87%E9%96%80%E6%99%82%E5%B0%9A%E6%B9%AF%E9%8D%8B%E6%96%B0%E7%AB%B9%E5%85%89%E5%BE%A9%E5%BA%97%EF%BD%9C%E7%AB%B9%E7%A7%91%E5%AE%B5%E5%A4%9C%E9%A6%96%E9%81%B8%E7%99%BE%E5%85%83%E5%B9%B3/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=六扇門新竹光復店",
  },
  {
    id: "city-jhujian-zhonghua",
    name: "築間幸福鍋物・新竹中華店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 500,
    hours: "每日 11:00 起；深夜閉店時間依官方據點頁當日公告",
    address: "新竹市香山區中華路五段 46 號",
    signature: "個人鍋、自助蔬食吧與深夜聚餐",
    note: "中價位火鍋的深夜選擇；假日與連假時段可能調整，出發前請先看官方據點頁。",
    parking: "開車較方便，停車方式依現場與官方據點說明。",
    sourceLabel: "築間｜官方據點資訊",
    sourceUrl: "https://www.jhujian.com.tw/jhujianshabu/tw/store",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=築間幸福鍋物新竹中華店",
  },
  {
    id: "city-guotanghui",
    name: "鍋湯滙 24H・新竹光復店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 400,
    hours: "標示 24 小時營業；外送暫停或臨時休息仍依店家當日狀態",
    address: "新竹市東區光復路一段 469 號",
    signature: "個人鍋、凌晨用餐與園區輪班補給",
    note: "適合錯過一般晚餐時段的人；第三方頁面曾出現臨時關閉回饋，出發前務必再次確認。",
    parking: "光復路沿線車流大，機車較方便；開車可找周邊收費停車場。",
    sourceLabel: "Uber Eats｜近期菜單與店況",
    sourceUrl: "https://www.ubereats.com/tw/store/%E9%8D%8B%E6%B9%AF%E5%8C%AF24h-%E6%96%B0%E7%AB%B9%E5%85%89%E5%BE%A9%E5%BA%97/SeXQ6bM7WGyvE-kS1KagqA",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=鍋湯匯24H新竹光復店",
  },
  {
    id: "city-thai-thai",
    name: "泰泰 Thai Thai 泰式料理",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["thai", "indian"],
    meals: ["lunch", "dinner"],
    budget: 180,
    hours: "週二至日 11:00–14:00、16:30–20:00；週一休",
    address: "新竹市東區食品路 273 號",
    signature: "打拋飯、椒麻雞與百元泰式簡餐",
    note: "適合一個人吃的平價泰式，咖哩飯也讓它同時出現在咖哩分類。",
    parking: "食品路車位有限，機車較方便；開車可找新竹公園周邊停車場。",
    reviewLabel: "Google 4.2（彙整頁）",
    reviewUrl: "https://blog.footinder.app/%E6%96%B0%E7%AB%B9%E5%B8%82%E6%9D%B1%E5%8D%80-2/%E6%96%B0%E7%AB%B9%E5%B8%82-%E6%9D%B1%E5%8D%80-%E6%B3%B0%E6%B3%B0-%E6%B3%B0%E5%BC%8F%E6%96%99%E7%90%86/",
    sourceLabel: "愛食記｜近期營業資訊",
    sourceUrl: "https://ifoodie.tw/restaurant/5c876b04f52468307bee22da",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=泰泰ThaiThai新竹食品路",
  },
  {
    id: "city-taibaoye",
    name: "泰飽爺・水田店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["thai", "indian"],
    meals: ["lunch", "dinner"],
    budget: 180,
    hours: "每日 11:00–21:30；不定休依店家公告",
    address: "新竹市北區水田街 147 號",
    signature: "打拋豬、椒麻雞與百元南洋咖哩飯",
    note: "份量與價格都適合平日快速吃；2025 年底食記仍有實際消費與營業資訊。",
    parking: "水田街路邊車位有限，建議機車或使用北大路周邊停車場。",
    sourceLabel: "PTT Food｜2025 實際消費資訊",
    sourceUrl: "https://www.ptt.cc/bbs/Food/M.1769745856.A.9E4.html",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=泰飽爺水田店",
  },
  {
    id: "city-thaifangxiang",
    name: "泰・方象泰國路邊攤",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["thai", "indian"],
    meals: ["lunch", "dinner"],
    budget: 350,
    hours: "每週營業日與時段變動較大；出發前請查看店家最新公告",
    address: "新竹市東區花園街 37 號",
    signature: "泰式炒河粉、咖哩與隱藏版路邊攤",
    note: "在地高人氣、但採周休多日的營業方式；適合願意先查公告再專程去吃。",
    parking: "花園街路幅較小，建議停在後站或新竹公園周邊再步行。",
    reviewLabel: "Google 4.5（媒體查核）",
    reviewUrl: "https://www.walkerland.com.tw/article/view/297339",
    sourceLabel: "近期食記｜營業與菜色查核",
    sourceUrl: "https://blake.com.tw/blog/post/tai-fang-xiang-202407",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=泰方象泰國路邊攤",
  },
  {
    id: "city-nara-thai",
    name: "NARA Thai Cuisine・新竹巨城店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["thai"],
    meals: ["lunch", "dinner"],
    budget: 700,
    hours: "週日至四 11:00–21:30；週五、六 11:00–22:00；依商場公告為準",
    address: "新竹市東區中央路 239 號 4 樓",
    signature: "泰式合菜、約會與精緻多人聚餐",
    note: "高價位泰式選擇之一，適合 3–4 人共享；單點數量與飲品會明顯影響人均。",
    parking: "可使用遠東巨城停車場，消費折抵依商場規則。",
    sourceLabel: "OpenTable｜近期營業資訊",
    sourceUrl: "https://www.opentable.com.tw/restaurant/profile/176483",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=NARAThaiCuisine新竹巨城店",
  },
  {
    id: "city-grassroots-kitchen",
    name: "草根廚房",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 700,
    hours: "每日 11:30–14:00、17:30–21:00；臨時公休依店家公告",
    address: "新竹市東區柴橋路 350 號",
    signature: "烤鴨多吃、台菜功夫菜與家庭聚餐",
    note: "把台式／小吃分類延伸到正式台菜；烤鴨通常需預訂，適合多人分食。",
    parking: "開車最方便；柴橋路周邊依現場指示停車，週末建議提早抵達。",
    sourceLabel: "聯合新聞網｜2025 店家查核",
    sourceUrl: "https://travel.udn.com/travel/story/7206/8911638",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=草根廚房新竹",
  },
  {
    id: "city-dintaifung",
    name: "鼎泰豐・新竹店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 650,
    hours: "平日 11:00–21:30；週五、六及例假日前一天至 22:00；依百貨公告為準",
    address: "新竹市東區西大路 323 號 B1",
    signature: "小籠包、麵點與高完成度台式聚餐",
    note: "從經典小吃升級到完整聚餐的高價位選擇；熱門時段候位時間可能較長。",
    parking: "可使用新竹大遠百停車場，折抵方式依百貨公告。",
    sourceLabel: "鼎泰豐｜官方門市資訊",
    sourceUrl: "https://www.dintaifung.com.tw/store.php",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=鼎泰豐新竹店",
  },
  {
    id: "zhubei-eleventh-street",
    name: "十一街麵食館",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 350,
    hours: "每日 10:30–20:30；臨時公休依店家公告",
    address: "新竹縣竹北市光明一路 275 號",
    signature: "北方麵食、合菜與家庭聚餐",
    note: "品項多、份量適合分享；人數多時比單點一碗麵更有彈性。",
    parking: "光明商圈有路邊格與公有停車場，週末用餐時段容易客滿。",
    sourceLabel: "交通部觀光署／FonFood",
    sourceUrl: "https://media.taiwan.net.tw/zh-tw/portal/travel/details/restaurant_376440000a_000172",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=十一街麵食館竹北",
  },
  {
    id: "zhubei-duanchunzhen",
    name: "段純貞牛肉麵・竹北店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 300,
    hours: "週二至五 11:30–14:00、17:30–20:30；週末午餐至 14:30；週一休",
    address: "新竹縣竹北市嘉豐六路一段 95 號",
    signature: "牛肉麵、紅油抄手與快速正餐",
    note: "靠近高鐵特區，適合看電影、逛街或搭車前後吃。",
    parking: "周邊有路邊停車格與停車場；尖峰時段仍建議提早抵達。",
    sourceLabel: "段純貞｜官方門市資訊",
    sourceUrl: "https://www.duanchunzhen.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=段純貞竹北店",
  },
  {
    id: "zhubei-yenchiang-hotpot",
    name: "岩漿火鍋・竹北復興店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["chinese", "hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 800,
    hours: "每日 11:00–24:00；最後入場 22:00",
    address: "新竹縣竹北市復興一街 236 號",
    signature: "麻辣鍋、鴛鴦鍋與晚間聚餐",
    note: "用餐時間可拉到午夜；若要 22:00 後入場，先電話確認最保險。",
    parking: "店家分店資訊標示有停車服務，依現場停車指引為準。",
    sourceLabel: "岩漿火鍋｜官方分店資訊",
    sourceUrl: "https://yenchiang-hotpot.com/index.php/branch/get_has_navi_page/1",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=岩漿火鍋竹北復興店",
  },
  {
    id: "zhubei-shinbashi-yakiniku",
    name: "新橋燒肉屋・竹北店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["japanese"],
    meals: ["lunch", "dinner"],
    budget: 900,
    hours: "平日 11:30–14:00、17:30–21:30；週末 11:30–14:30、17:00–21:30",
    address: "新竹縣竹北市光明一路 277 號",
    signature: "日式燒肉與光明商圈聚餐",
    note: "適合兩人以上聚餐；預算以每人約 NT$900 估算，酒水另計。",
    parking: "可使用光明商圈公有停車場，晚餐尖峰建議先停好再步行。",
    sourceLabel: "OpenTable｜店家營業資訊",
    sourceUrl: "https://www.opentable.com.tw/restaurant/profile/210197",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=新橋燒肉屋竹北店",
  },
  {
    id: "zhubei-sishi-skewers",
    name: "私嚐串燒・竹北店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["japanese", "late"],
    meals: ["dinner", "late"],
    budget: 700,
    hours: "18:00 起；閉店時間與公休日請依官方帳號當日公告",
    address: "新竹縣竹北市光明一路 70 號",
    signature: "串燒、居酒屋與朋友續攤",
    note: "官方帳號列有竹北分店電話與地址；深夜前往前建議先確認當日營業。",
    parking: "光明商圈路邊格有限，可利用鄰近公有停車場後步行。",
    sourceLabel: "私嚐｜LINE 官方帳號",
    sourceUrl: "https://page.line.me/kuu0879e",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=私嚐串燒竹北店",
  },
  {
    id: "zhubei-ippudo",
    name: "一風堂・竹北遠百店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["japanese"],
    meals: ["lunch", "dinner"],
    budget: 350,
    hours: "週日至四 11:00–21:30；週五、六 11:00–22:00；依商場公告為準",
    address: "新竹縣竹北市莊敬北路 18 號 B2",
    signature: "博多豚骨拉麵與竹北逛街午晚餐",
    note: "中價位日式的第二個選擇，點主餐加小菜仍可把人均控制在 NT$500 內。",
    parking: "可使用遠百竹北停車場，消費折抵依商場規則。",
    sourceLabel: "一風堂｜官方店舖資訊",
    sourceUrl: "https://www.ippudo.com.tw/branch/1/2",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=一風堂竹北遠百店",
  },
  {
    id: "zhubei-three-moms",
    name: "三媽臭臭鍋・竹北竹仁店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 190,
    hours: "每日 11:00–23:00；臨時異動依店家公告",
    address: "新竹縣竹北市中正東路 160 號",
    signature: "百元臭臭鍋、個人晚餐與晚間加餐",
    note: "平價火鍋的第二個選擇；Uber Eats 近期頁面顯示 4.87 分。",
    parking: "中正東路車流較多，機車較方便；開車可找竹仁市場周邊停車格。",
    reviewLabel: "Uber Eats 4.87",
    reviewUrl: "https://www.ubereats.com/tw/store/%E4%B8%89%E5%AA%BD%E8%87%AD%E8%87%AD%E9%8D%8B%E7%AB%B9%E5%8C%97%E7%AB%B9%E4%BB%81%E5%BA%97/N9a5C4yIQciei9e9cc0nkQ",
    sourceLabel: "FooTinder｜近期營業資訊",
    sourceUrl: "https://footinder.com.tw/%E6%96%B0%E7%AB%B9%E7%B8%A3%E7%AB%B9%E5%8C%97%E5%B8%82/123289/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=三媽臭臭鍋竹北竹仁店",
  },
  {
    id: "zhubei-siammore",
    name: "饗泰多・竹北遠百店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["thai", "indian"],
    meals: ["lunch", "dinner"],
    budget: 700,
    hours: "每日 11:00–22:00；依商場公告與訂位時段為準",
    address: "新竹縣竹北市莊敬北路 18 號 7 樓",
    signature: "泰式合菜、黃咖哩與多人慶祝聚餐",
    note: "高價位泰式／咖哩選擇；Uber Eats 近期頁面顯示 4.88 分，適合多人共享。",
    parking: "可使用遠百竹北停車場，消費折抵依商場規則。",
    reviewLabel: "Uber Eats 4.88",
    reviewUrl: "https://www.ubereats.com/tw/store/%E9%A5%97%E6%B3%B0%E5%A4%9A-%E7%AB%B9%E5%8C%97%E9%81%A0%E7%99%BE%E5%BA%97/b-fNA4ONWdGEsIP6feKtFg",
    sourceLabel: "遠百竹北｜官方樓層資訊",
    sourceUrl: "https://aws.feds.com.tw/tw/42/MallInfo/FloorRestaurant?FloorId=86&RestaurantId=138&tab=floor-3F",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=饗泰多竹北遠百店",
  },
  {
    id: "zhudong-huangji",
    name: "黃記粄條商行",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 150,
    hours: "每日 06:00–13:20、15:30–19:00",
    address: "新竹縣竹東鎮大明路 10 號",
    signature: "客家粄條與早午餐型小吃",
    note: "想避開排隊可早一點到；下午有休息時段，不要卡在 13:20 後。",
    parking: "竹東市區以機車較方便；開車可找仁愛路、公園路周邊停車格。",
    sourceLabel: "竹東鎮觀光休閒網",
    sourceUrl: "https://www.zdhakka.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=黃記粄條商行竹東",
  },
  {
    id: "zhudong-chenji-noodles",
    name: "陳記老街麵店",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 150,
    hours: "週三至一 06:30–20:00；週二休",
    address: "新竹縣竹東鎮榮樂街 48 號",
    signature: "老街乾麵、湯品與銅板小吃",
    note: "靠近竹東市場與老街，適合排進半日散步路線。",
    parking: "建議停在竹東鎮公有停車場，再步行逛市場與榮樂街。",
    sourceLabel: "竹東鎮觀光休閒網",
    sourceUrl: "https://www.zdhakka.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=陳記老街麵店竹東",
  },
  {
    id: "zhudong-good-place",
    name: "好所在客家美食館",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese"],
    meals: ["lunch", "dinner"],
    budget: 500,
    hours: "週五至一 11:00–14:30、17:00–20:00；週二至四休",
    address: "新竹縣竹東鎮東峰路 228 號",
    signature: "客家合菜與家庭聚餐",
    note: "公休日較多，適合先確認再出發；多人點合菜較能控制人均預算。",
    parking: "店家位於東峰路，開車最方便；停車方式依現場指示。",
    sourceLabel: "竹東鎮觀光休閒網",
    sourceUrl: "https://www.zdhakka.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=好所在客家美食館竹東",
  },
  {
    id: "zhudong-zhuangji-beef-noodles",
    name: "莊記牛肉麵",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 200,
    hours: "週一至六 10:00–20:00；週日休",
    address: "新竹縣竹東鎮仁愛路 248 號",
    signature: "牛肉麵與竹東在地午晚餐",
    note: "選擇直接、預算好抓，適合臨時決定或一個人用餐。",
    parking: "仁愛路周邊車流多，機車較方便；開車可找公有停車場。",
    sourceLabel: "竹東鎮觀光休閒網",
    sourceUrl: "https://www.zdhakka.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=莊記牛肉麵竹東",
  },
  {
    id: "zhudong-yenchiang-hotpot",
    name: "岩漿火鍋・新竹明星店",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese", "hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 800,
    hours: "每日 11:00–24:00；最後入場 22:00",
    address: "新竹縣竹東鎮明星一路 110 號",
    signature: "麻辣火鍋、竹科聚餐與晚餐續攤",
    note: "位於竹東靠竹科一側；要安排深夜時段，先確認最後入場時間。",
    parking: "店家分店資訊標示有停車服務，依現場安排為準。",
    sourceLabel: "岩漿火鍋｜官方分店資訊",
    sourceUrl: "https://yenchiang-hotpot.com/index.php/branch/get_has_navi_page/1",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=岩漿火鍋新竹明星店",
  },
  {
    id: "guanpu-mozhuting",
    name: "墨竹亭・新竹金山店",
    region: "guanpu",
    regionLabel: "關埔・園區",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 180,
    hours: "每日 11:30–20:30；臨時異動依官方門市公告",
    address: "新竹市東區金山十一街 31 號",
    signature: "川味燃麵、餛飩與一人快速用餐",
    note: "金山街的平價麵食選項；彙整頁收錄超過兩千則 Google 評論，適合園區午休或下班直接吃。",
    parking: "金山街停車不易，機車最方便；開車建議停外圍再步行。",
    reviewLabel: "Google 4.6／2,114 則",
    reviewUrl: "https://footinder.com.tw/%E6%96%B0%E7%AB%B9%E5%B8%82%E6%9D%B1%E5%8D%80/64235/",
    sourceLabel: "墨竹亭｜官方門市資訊",
    sourceUrl: "https://www.mozhuting.com/store/jinshan",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=墨竹亭新竹金山店",
  },
  {
    id: "guanpu-whiskers",
    name: "鬍鬚張・新竹關新店",
    region: "guanpu",
    regionLabel: "關埔・園區",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 180,
    hours: "每日 10:30–21:30",
    address: "新竹市東區關新路 177 號",
    signature: "魯肉飯、雞魯飯與穩定快速的台式正餐",
    note: "價位容易控制，Uber Eats 近期頁面評價達 4.91；趕時間或一個人吃都很直接。",
    parking: "距新莊車站步行可達；開車可找關新路周邊停車場。",
    reviewLabel: "Uber Eats 4.91",
    reviewUrl: "https://www.ubereats.com/tw/store/%E9%AC%8D%E9%AC%9A%E5%BC%B5-%E6%96%B0%E7%AB%B9%E9%97%9C%E6%96%B0%E5%BA%97/jM4VEC2KSueyQU4YcviYbw",
    sourceLabel: "鬍鬚張｜官方門市資訊",
    sourceUrl: "https://shop.fmsc.com.tw/pages/%E9%96%80%E5%B8%82%E8%B3%87%E8%A8%8A",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=鬍鬚張新竹關新店",
  },
  {
    id: "guanpu-thai-town",
    name: "瓦城・新竹關新店",
    region: "guanpu",
    regionLabel: "關埔・園區",
    tags: ["thai", "indian"],
    meals: ["lunch", "dinner"],
    budget: 450,
    hours: "平日 11:30–14:30、17:30–21:30；週末午餐至 15:00",
    address: "新竹市東區關新路 79 號 2 樓",
    signature: "泰式合菜、家庭聚餐與部門聚會",
    note: "適合三人以上共享；近期 foodpanda 評分 4.6，月亮蝦餅、咖哩與蝦醬系列容易搭配。",
    parking: "關新路周邊有收費停車場；週末晚餐建議先訂位。",
    reviewLabel: "foodpanda 4.6／19 則",
    reviewUrl: "https://www.foodpanda.com.tw/restaurant/ini8/wa-cheng-tai-guo-liao-li-xin-zhu-guan-xin-dian",
    sourceLabel: "OpenTable｜近期營業資訊",
    sourceUrl: "https://www.opentable.com.tw/restaurant/profile/189854",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=瓦城新竹關新店",
  },
  {
    id: "guanpu-1010-hunan",
    name: "1010 湘・新竹關新店",
    region: "guanpu",
    regionLabel: "關埔・園區",
    tags: ["chinese"],
    meals: ["lunch", "dinner"],
    budget: 500,
    hours: "平日 11:30–14:30、17:30–21:30；週末午餐至 15:00",
    address: "新竹市東區關新路 81 號 2 樓",
    signature: "湘菜、重口味合菜與多人聚餐",
    note: "Tripadvisor 近期頁面為 4.3 分；適合喜歡辣味、需要多人分菜的晚餐。",
    parking: "可使用關新路周邊收費停車場；兩人用餐較難多點菜。",
    reviewLabel: "Tripadvisor 4.3／5",
    reviewUrl: "https://www.tripadvisor.com.tw/Restaurant_Review-g13806499-d15122903-Reviews-1010_Hunan_Cuisine_Hsinchu_Guanxin_Store-East_District_Hsinchu.html",
    sourceLabel: "OpenTable｜近期營業資訊",
    sourceUrl: "https://www.opentable.com.tw/restaurant/profile/189881",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=1010湘新竹關新店",
  },
  {
    id: "guanpu-ke-rou-hotpot",
    name: "嗑肉石鍋・新竹金山店",
    region: "guanpu",
    regionLabel: "關埔・園區",
    tags: ["hotpot"],
    meals: ["lunch", "dinner"],
    budget: 500,
    hours: "平日 11:30–15:15、17:30–22:45；週末時段依訂位頁公告",
    address: "新竹市東區金山十街 56 號",
    signature: "個人石頭火鍋、肉量選擇與園區晚餐",
    note: "彙整頁網友評分 4.6；一人一鍋比合菜更適合臨時約，也能各自控制預算。",
    parking: "店家未提供停車場；金山街建議騎機車或停外圍。",
    reviewLabel: "Google 4.6（彙整頁）",
    reviewUrl: "https://footinder.com.tw/%E6%96%B0%E7%AB%B9%E5%B8%82%E6%9D%B1%E5%8D%80/123212/",
    sourceLabel: "OpenTable｜近期營業資訊",
    sourceUrl: "https://www.opentable.com.tw/restaurant/profile/178910",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=嗑肉石鍋新竹金山店",
  },
  {
    id: "guanpu-abv-japanese",
    name: "ABV 日式居酒館・新竹關新店",
    region: "guanpu",
    regionLabel: "關埔・園區",
    tags: ["japanese", "late"],
    meals: ["dinner", "late"],
    budget: 900,
    hours: "每日 16:00–02:00",
    address: "新竹市東區關新路 173 號",
    signature: "日式居酒屋、精釀啤酒與深夜聚餐",
    note: "彙整頁收錄超過千則評論、評分 4.7；優勢是營業到深夜與酒款選擇多。",
    parking: "新莊車站步行約 3 分鐘；喝酒建議搭車，不要自行開車。",
    reviewLabel: "Google 4.7／1,259 則",
    reviewUrl: "https://footinder.com.tw/%E6%96%B0%E7%AB%B9%E5%B8%82%E6%9D%B1%E5%8D%80/160290/",
    sourceLabel: "ABV｜官方門市資訊",
    sourceUrl: "https://www.abv.com.tw/contact-us/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=ABV日式居酒館新竹關新店",
  },
  {
    id: "guanpu-chillies",
    name: "淇里思印度餐廳・新竹店",
    region: "guanpu",
    regionLabel: "關埔・園區",
    tags: ["indian"],
    meals: ["lunch", "dinner"],
    budget: 700,
    hours: "平日 11:00–14:30、17:00–21:00；週末 11:00–15:00、17:00–21:30",
    address: "新竹市東區關新西街 100 號",
    signature: "印度咖哩、烤餅與多人分享料理",
    note: "近期彙整頁顯示 4.8 分、超過六千則評價；想換口味或招待外地朋友很合適。",
    parking: "附近有停車空間但數量有限；尖峰時段建議提早抵達。",
    reviewLabel: "Google 4.8／6,323 則",
    reviewUrl: "https://food.timetables.tw/restaurant/ChIJcS_5czk2aDQR7bnj8wtHhYM/",
    sourceLabel: "OpenTable｜近期營業資訊",
    sourceUrl: "https://www.opentable.com.tw/restaurant/profile/177227",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=淇里思印度餐廳新竹店",
  },
  {
    id: "guanpu-royal-teppanyaki",
    name: "老爺鐵板燒",
    region: "guanpu",
    regionLabel: "關埔・園區",
    tags: ["japanese"],
    meals: ["lunch", "dinner"],
    budget: 1800,
    hours: "週一至六 11:30–14:00、17:30–21:00；週日休",
    address: "新竹市東區光復路一段 227 號 2 樓",
    signature: "飯店鐵板燒、紀念日與正式聚餐",
    note: "網友評分彙整為 4.2；屬於高價位選擇，午餐通常比晚餐容易控制預算。",
    parking: "位於新竹老爺酒店內，可依飯店停車與消費折抵規則使用。",
    reviewLabel: "Google 4.2（彙整頁）",
    reviewUrl: "https://footinder.com.tw/%E6%96%B0%E7%AB%B9%E5%B8%82%E6%9D%B1%E5%8D%80/174328/",
    sourceLabel: "新竹老爺酒店｜官方資訊",
    sourceUrl: "https://www.hotelroyal.com.tw/zh-tw/hsinchu/dining/1462",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=新竹老爺酒店老爺鐵板燒",
  },
].map((restaurant) => ({
  ...restaurant,
  priceTier: restaurant.budget <= 200 ? "value" : restaurant.budget <= 500 ? "mid" : "premium",
}));

export function filterRestaurants(catalog, filters = {}) {
  const {
    region = "all",
    category = "all",
    meal = "all",
    priceTier = "all",
  } = filters;

  return catalog.filter((restaurant) => {
    const regionMatches = region === "all" || restaurant.region === region;
    const categoryMatches = category === "all" || restaurant.tags.includes(category);
    const mealMatches = meal === "all" || restaurant.meals.includes(meal);
    const priceMatches = priceTier === "all" || restaurant.priceTier === priceTier;

    return regionMatches && categoryMatches && mealMatches && priceMatches;
  });
}
