export const restaurantRegions = [
  { id: "all", label: "全部地區" },
  { id: "city", label: "新竹市區" },
  { id: "zhubei", label: "竹北" },
  { id: "zhudong", label: "竹東" },
];

export const restaurantCategories = [
  { id: "all", label: "全部類型" },
  { id: "japanese", label: "日式" },
  { id: "chinese", label: "中式" },
  { id: "snack", label: "小吃" },
  { id: "late", label: "宵夜" },
  { id: "hotpot", label: "火鍋" },
];

export const restaurantMeals = [
  { id: "all", label: "不限時段" },
  { id: "lunch", label: "午餐" },
  { id: "dinner", label: "晚餐" },
  { id: "late", label: "深夜" },
];

export const restaurantTagLabels = {
  japanese: "日式",
  chinese: "中式",
  snack: "小吃",
  late: "宵夜",
  hotpot: "火鍋",
};

export const restaurants = [
  {
    id: "city-duck-rice",
    name: "廟口鴨香飯・中正店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 150,
    hours: "週一、四至日 11:00–15:00、15:30–20:40；週二、三休",
    address: "新竹市北區中正路 258 號",
    signature: "鴨香飯、鴨肉與在地小吃",
    note: "適合一個人快速吃，也適合把小菜分著點。尖峰時段通常需要候位。",
    parking: "建議步行或機車；開車可找北門街、中正路周邊停車場。",
    sourceLabel: "FonFood｜近期營業資訊",
    sourceUrl: "https://www.fonfood.com/store/258557",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=廟口鴨香飯中正店",
  },
  {
    id: "city-sishi-skewers",
    name: "私嚐串燒・中正店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["japanese", "late"],
    meals: ["dinner", "late"],
    budget: 700,
    hours: "週日至四 18:00–01:30；週五、六 18:00–02:00",
    address: "新竹市東區中正路 96 巷 8 號",
    signature: "串燒、居酒屋與深夜聚餐",
    note: "官方帳號可查訂位方式；多人聚餐或週末晚餐建議先訂位。",
    parking: "位於城隍廟商圈，建議搭車或步行；開車可利用府後街停車場。",
    sourceLabel: "私嚐｜LINE 官方帳號",
    sourceUrl: "https://page.line.me/kuu0879e",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=私嚐串燒中正店",
  },
  {
    id: "city-shinbashi-yakiniku",
    name: "新橋燒肉屋・府後店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["japanese"],
    meals: ["lunch", "dinner"],
    budget: 900,
    hours: "11:30–14:30、17:30–24:00；訂位與臨時異動依店家公告",
    address: "新竹市東區府後街 9 號",
    signature: "日式燒肉、約會與多人聚餐",
    note: "預算以每人約 NT$900 估算；實際依肉品與酒水選擇浮動。",
    parking: "可利用府後街停車場；週末晚餐時段建議預留找車位時間。",
    sourceLabel: "新橋燒肉｜官方訂位資訊",
    sourceUrl: "https://www.shinchiao.com.tw/shinbashi_yakiniku/reservation.asp",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=新橋燒肉屋府後店",
  },
  {
    id: "city-yenchiang-hotpot",
    name: "岩漿火鍋・新竹經國店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["chinese", "hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 800,
    hours: "每日 11:00–03:00；最後入場 02:00",
    address: "新竹市北區東大路二段 78 號",
    signature: "麻辣火鍋、聚餐與深夜熱食",
    note: "跨午餐到深夜都能用；宵夜時段仍建議先確認當日候位狀況。",
    parking: "店家分店資訊標示有停車服務，仍以現場安排為準。",
    sourceLabel: "岩漿火鍋｜官方分店資訊",
    sourceUrl: "https://yenchiang-hotpot.com/index.php/branch/get_has_navi_page/1",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=岩漿火鍋新竹經國店",
  },
  {
    id: "city-duanchunzhen",
    name: "段純貞牛肉麵・新竹建功店",
    region: "city",
    regionLabel: "新竹市區",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 300,
    hours: "週二至五 11:30–14:00、17:30–20:30；週末午餐至 14:30；週一休",
    address: "新竹市東區建功一路 135 號",
    signature: "紅燒牛肉麵與眷村風味",
    note: "清楚、好決定的一餐，適合交大商圈活動前後安排。",
    parking: "建功一路車位有限，機車較方便；開車可找赤土崎公園周邊停車場。",
    sourceLabel: "段純貞｜官方門市資訊",
    sourceUrl: "https://www.duanchunzhen.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=段純貞新竹建功店",
  },
  {
    id: "zhubei-eleventh-street",
    name: "十一街麵食館",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 350,
    hours: "每日 10:30–20:30；臨時公休依店家公告",
    address: "新竹縣竹北市光明一路 275 號",
    signature: "北方麵食、合菜與家庭聚餐",
    note: "品項多、份量適合分享；人數多時比單點一碗麵更有彈性。",
    parking: "光明商圈有路邊格與公有停車場，週末用餐時段容易客滿。",
    sourceLabel: "交通部觀光署／FonFood",
    sourceUrl: "https://media.taiwan.net.tw/zh-tw/portal/travel/details/restaurant_376440000a_000172",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=十一街麵食館竹北",
  },
  {
    id: "zhubei-duanchunzhen",
    name: "段純貞牛肉麵・竹北店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 300,
    hours: "週二至五 11:30–14:00、17:30–20:30；週末午餐至 14:30；週一休",
    address: "新竹縣竹北市嘉豐六路一段 95 號",
    signature: "牛肉麵、紅油抄手與快速正餐",
    note: "靠近高鐵特區，適合看電影、逛街或搭車前後吃。",
    parking: "周邊有路邊停車格與停車場；尖峰時段仍建議提早抵達。",
    sourceLabel: "段純貞｜官方門市資訊",
    sourceUrl: "https://www.duanchunzhen.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=段純貞竹北店",
  },
  {
    id: "zhubei-yenchiang-hotpot",
    name: "岩漿火鍋・竹北復興店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["chinese", "hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 800,
    hours: "每日 11:00–24:00；最後入場 22:00",
    address: "新竹縣竹北市復興一街 236 號",
    signature: "麻辣鍋、鴛鴦鍋與晚間聚餐",
    note: "用餐時間可拉到午夜；若要 22:00 後入場，先電話確認最保險。",
    parking: "店家分店資訊標示有停車服務，依現場停車指引為準。",
    sourceLabel: "岩漿火鍋｜官方分店資訊",
    sourceUrl: "https://yenchiang-hotpot.com/index.php/branch/get_has_navi_page/1",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=岩漿火鍋竹北復興店",
  },
  {
    id: "zhubei-shinbashi-yakiniku",
    name: "新橋燒肉屋・竹北店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["japanese"],
    meals: ["lunch", "dinner"],
    budget: 900,
    hours: "平日 11:30–14:00、17:30–21:30；週末 11:30–14:30、17:00–21:30",
    address: "新竹縣竹北市光明一路 277 號",
    signature: "日式燒肉與光明商圈聚餐",
    note: "適合兩人以上聚餐；預算以每人約 NT$900 估算，酒水另計。",
    parking: "可使用光明商圈公有停車場，晚餐尖峰建議先停好再步行。",
    sourceLabel: "OpenTable｜店家營業資訊",
    sourceUrl: "https://www.opentable.com.tw/restaurant/profile/210197",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=新橋燒肉屋竹北店",
  },
  {
    id: "zhubei-sishi-skewers",
    name: "私嚐串燒・竹北店",
    region: "zhubei",
    regionLabel: "竹北",
    tags: ["japanese", "late"],
    meals: ["dinner", "late"],
    budget: 700,
    hours: "18:00 起；閉店時間與公休日請依官方帳號當日公告",
    address: "新竹縣竹北市光明一路 70 號",
    signature: "串燒、居酒屋與朋友續攤",
    note: "官方帳號列有竹北分店電話與地址；深夜前往前建議先確認當日營業。",
    parking: "光明商圈路邊格有限，可利用鄰近公有停車場後步行。",
    sourceLabel: "私嚐｜LINE 官方帳號",
    sourceUrl: "https://page.line.me/kuu0879e",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=私嚐串燒竹北店",
  },
  {
    id: "zhudong-huangji",
    name: "黃記粄條商行",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 150,
    hours: "每日 06:00–13:20、15:30–19:00",
    address: "新竹縣竹東鎮大明路 10 號",
    signature: "客家粄條與早午餐型小吃",
    note: "想避開排隊可早一點到；下午有休息時段，不要卡在 13:20 後。",
    parking: "竹東市區以機車較方便；開車可找仁愛路、公園路周邊停車格。",
    sourceLabel: "竹東鎮觀光休閒網",
    sourceUrl: "https://www.zdhakka.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=黃記粄條商行竹東",
  },
  {
    id: "zhudong-chenji-noodles",
    name: "陳記老街麵店",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 150,
    hours: "週三至一 06:30–20:00；週二休",
    address: "新竹縣竹東鎮榮樂街 48 號",
    signature: "老街乾麵、湯品與銅板小吃",
    note: "靠近竹東市場與老街，適合排進半日散步路線。",
    parking: "建議停在竹東鎮公有停車場，再步行逛市場與榮樂街。",
    sourceLabel: "竹東鎮觀光休閒網",
    sourceUrl: "https://www.zdhakka.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=陳記老街麵店竹東",
  },
  {
    id: "zhudong-good-place",
    name: "好所在客家美食館",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese"],
    meals: ["lunch", "dinner"],
    budget: 500,
    hours: "週五至一 11:00–14:30、17:00–20:00；週二至四休",
    address: "新竹縣竹東鎮東峰路 228 號",
    signature: "客家合菜與家庭聚餐",
    note: "公休日較多，適合先確認再出發；多人點合菜較能控制人均預算。",
    parking: "店家位於東峰路，開車最方便；停車方式依現場指示。",
    sourceLabel: "竹東鎮觀光休閒網",
    sourceUrl: "https://www.zdhakka.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=好所在客家美食館竹東",
  },
  {
    id: "zhudong-zhuangji-beef-noodles",
    name: "莊記牛肉麵",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese", "snack"],
    meals: ["lunch", "dinner"],
    budget: 200,
    hours: "週一至六 10:00–20:00；週日休",
    address: "新竹縣竹東鎮仁愛路 248 號",
    signature: "牛肉麵與竹東在地午晚餐",
    note: "選擇直接、預算好抓，適合臨時決定或一個人用餐。",
    parking: "仁愛路周邊車流多，機車較方便；開車可找公有停車場。",
    sourceLabel: "竹東鎮觀光休閒網",
    sourceUrl: "https://www.zdhakka.com/",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=莊記牛肉麵竹東",
  },
  {
    id: "zhudong-yenchiang-hotpot",
    name: "岩漿火鍋・新竹明星店",
    region: "zhudong",
    regionLabel: "竹東",
    tags: ["chinese", "hotpot", "late"],
    meals: ["lunch", "dinner", "late"],
    budget: 800,
    hours: "每日 11:00–24:00；最後入場 22:00",
    address: "新竹縣竹東鎮明星一路 110 號",
    signature: "麻辣火鍋、竹科聚餐與晚餐續攤",
    note: "位於竹東靠竹科一側；要安排深夜時段，先確認最後入場時間。",
    parking: "店家分店資訊標示有停車服務，依現場安排為準。",
    sourceLabel: "岩漿火鍋｜官方分店資訊",
    sourceUrl: "https://yenchiang-hotpot.com/index.php/branch/get_has_navi_page/1",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=岩漿火鍋新竹明星店",
  },
];

export function filterRestaurants(catalog, filters = {}) {
  const {
    region = "all",
    category = "all",
    meal = "all",
    budget = Number.POSITIVE_INFINITY,
  } = filters;

  return catalog.filter((restaurant) => {
    const regionMatches = region === "all" || restaurant.region === region;
    const categoryMatches = category === "all" || restaurant.tags.includes(category);
    const mealMatches = meal === "all" || restaurant.meals.includes(meal);
    const budgetMatches = restaurant.budget <= budget;

    return regionMatches && categoryMatches && mealMatches && budgetMatches;
  });
}
